#Title: Memory game


* Learning Objectives
 Change things in the DOM (Aka canvas = cheating)
* Array manipulation


The Mission
------------
We want to recreate the game `memory`. It is a game where  you have a bunch of cards. Each card contains an image. 
Of each image there are exactly two cards. The cards are placed in a random order. You get to turn them around. 
If you turned around two cards they either turn back so you can't see their image if they did not match. 
And if they did match they stay image face visible.

Nice-to-have features
- Make it playable by keyboard
- Let a user define custom image urls
- Make it pleasing to look at
- Multiplayer (local)

Tips (You might want to only read this if you are stuck)

Here is a good way to split up the work. You might want to try to split it up even further:

- Have a bunch of square images (hard code their order, use html)
- Make them turn on click
- Make their order random using javascript
- Turn them back around if you clicked two
- Then implement the logic to only turn back if they don't match

MY CODE
_________

1. 10 cards: different front, same background => 11 images
2. lay out: grid
3. functions: ad random

* CSS:

     Position your DIVs within a parent DIV with display: flex
     Set each of the children display: none

* JS:

    select the children of the parent DIV.
    create an array of references to the selected divs
    Use shuffleArray to randomize the order of the array elements
    Iterate the array of references and use the array order to position the child divs -
    document.getElementByID(arr).style.order = array_element_number
    document.getElementByID(arr).style.display = ‘block’
    /* Randomize array in-place using Durstenfeld shuffle algorithm */
    function shuffleArray(array) {
    for (var i = array.length - 1; i > 0; i--) {
    var j = Math.floor(Math.random() * (i + 1));
    var temp = array[i];
    array[i] = array[j];
    array[j] = temp;
    }
    }
4. turn card: click event : change image
5. timer to turn back if 2 different cards <-> remove if same cards
